tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
ports:
  - port: 5432
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 8088
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker