version: '2.4'

services:
  hoppscotch:
    image: hoppscotch/hoppscotch:latest
    container_name: hds-hoppscotch
    depends_on:
      - 'hasura'
      - 'django'
    ports:
      - "127.0.0.1:3000:3000"