# Generated by Django 3.2.12 on 2022-03-05 22:23

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(default=api.models.get_user_role, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
